version: "3.8"
services:
  chatbot_statistic_api:
    image: chatbot-statistic-api
    ports:
      - 8000:8000
    environment:
      - CLICK_HOUSE_HOST=localhost
      - CLICK_HOUSE_PORT=9000
      - CLICK_HOUSE_HTTP_PORT=8123
      - CLICK_HOUSE_DB=statistic_log
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=8000
      - COUNT_WORKERS_UVICORN=4
      - CLICK_HOUSE_USER=admin_user
      - CLICK_HOUSE_PASSWORD=secure_password_123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
